version: "3"
services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
    ports:
        - "3306:3306"
    command: -p 3306
